double* broyden(double*);
double f1(double, double);
double f2(double, double);
double* vecmatmul(double*, double*);
double* vecdiff(double*, double*);
double squaredifference(double*, double*);
double* veccvecrmul(double*, double*);
double vecrveccmul(double*, double*);
double* matmatmul(double*, double*);
double* matvecmul(double*, double*);
