subroutine DPLPFE (MRELAS, NVARS, LMX, LBM, IENTER, IBASIS, IMAT, &
     IBRC, IPR, IWR, IND, IBB, ERDNRM, EPS, GG, DULNRM, DIRNRM, &
     AMAT, BASMAT, CSC, WR, WW, BL, BU, RZ, RG, COLNRM, DUALS, &
     FOUND)
!
!! DPLPFE is subsidiary to DSPLP.
!
!***LIBRARY   SLATEC
!***TYPE      DOUBLE PRECISION (SPLPFE-S, DPLPFE-D)
!***AUTHOR  (UNKNOWN)
!***DESCRIPTION
!
!     THE EDITING REQUIRED TO CONVERT THIS SUBROUTINE FROM SINGLE TO
!     DOUBLE PRECISION INVOLVES THE FOLLOWING CHARACTER STRING CHANGES.
!
!     USE AN EDITING COMMAND (CHANGE) /STRING-1/(TO)STRING-2/.
!     /REAL (12 BLANKS)/DOUBLE PRECISION/,/SASUM/DASUM/,
!     /SCOPY/DCOPY/.
!
!     THIS SUBPROGRAM IS PART OF THE DSPLP( ) PACKAGE.
!     IT IMPLEMENTS THE PROCEDURE (FIND VARIABLE TO ENTER BASIS
!     AND GET SEARCH DIRECTION).
!     REVISED 811130-1100
!     REVISED YYMMDD-HHMM
!
!***SEE ALSO  DSPLP
!***ROUTINES CALLED  DASUM, DCOPY, DPRWPG, IDLOC, LA05BD
!***REVISION HISTORY  (YYMMDD)
!   811215  DATE WRITTEN
!   890531  Changed all specific intrinsics to generic.  (WRB)
!   890605  Removed unreferenced labels.  (WRB)
!   890606  Changed references from IPLOC to IDLOC.  (WRB)
!   891214  Prologue converted to Version 4.0 format.  (BAB)
!   900328  Added TYPE section.  (WRB)
!***END PROLOGUE  DPLPFE
  INTEGER IBASIS(*),IMAT(*),IBRC(LBM,2),IPR(*),IWR(*),IND(*),IBB(*)
  DOUBLE PRECISION AMAT(*),BASMAT(*),CSC(*),WR(*),WW(*),BL(*),BU(*), &
   RZ(*),RG(*),COLNRM(*),DUALS(*),CNORM,DIRNRM,DULNRM,EPS,ERDNRM,GG, &
   ONE,RATIO,RCOST,RMAX,ZERO
  DOUBLE PRECISION DASUM
  LOGICAL FOUND,TRANS
!***FIRST EXECUTABLE STATEMENT  DPLPFE
  LPG=LMX-(NVARS+4)
  ZERO=0.D0
  ONE=1.D0
  RMAX=ZERO
  FOUND=.FALSE.
  I=MRELAS+1
  N20002=MRELAS+NVARS
  go to 20003
20002 I=I+1
20003 if ((N20002-I) < 0) go to 20004
  J=IBASIS(I)
!
!     if J=IBASIS(I)  <  0 THEN THE VARIABLE LEFT AT A ZERO LEVEL
!     AND IS NOT CONSIDERED AS A CANDIDATE TO ENTER.
  if (.NOT.(J > 0)) go to 20006
!
!     DO NOT CONSIDER VARIABLES CORRESPONDING TO UNBOUNDED STEP LENGTHS.
  if (.NOT.(IBB(J) == 0)) go to 20009
  go to 20002
20009 CONTINUE
!
!     if A VARIABLE CORRESPONDS TO AN EQUATION(IND=3 AND BL=BU),
!     THEN DO NOT CONSIDER IT AS A CANDIDATE TO ENTER.
  if (.NOT.(IND(J) == 3)) go to 20012
  if (.NOT.((BU(J)-BL(J)) <= EPS*(ABS(BL(J))+ABS(BU(J))))) &
  go to 20015
  go to 20002
20015 CONTINUE
  CONTINUE
20012 CONTINUE
  RCOST=RZ(J)
!
!     if VARIABLE IS AT UPPER BOUND IT CAN ONLY DECREASE.  THIS
!     ACCOUNTS FOR THE POSSIBLE CHANGE OF SIGN.
  if ( MOD(IBB(J),2) == 0) RCOST=-RCOST
!
!     if THE VARIABLE IS FREE, USE THE NEGATIVE MAGNITUDE OF THE
!     REDUCED COST FOR THAT VARIABLE.
  if ( IND(J) == 4) RCOST=-ABS(RCOST)
  CNORM=ONE
  if ( J <= NVARS)CNORM=COLNRM(J)
!
!     TEST FOR NEGATIVITY OF REDUCED COSTS.
  if (.NOT.(RCOST+ERDNRM*DULNRM*CNORM < ZERO)) go to 20018
  FOUND=.TRUE.
  RATIO=RCOST**2/RG(J)
  if (.NOT.(RATIO > RMAX)) go to 20021
  RMAX=RATIO
  IENTER=I
20021 CONTINUE
  CONTINUE
20018 CONTINUE
  CONTINUE
20006 go to 20002
!
!     USE COL. CHOSEN TO COMPUTE SEARCH DIRECTION.
20004 if (.NOT.(FOUND)) go to 20024
  J=IBASIS(IENTER)
  WW(1)=ZERO
  call DCOPY(MRELAS,WW,0,WW,1)
  if (.NOT.(J <= NVARS)) go to 20027
  if (.NOT.(J == 1)) go to 20030
  ILOW=NVARS+5
  go to 20031
20030 ILOW=IMAT(J+3)+1
20031 CONTINUE
  IL1=IDLOC(ILOW,AMAT,IMAT)
  if (.NOT.(IL1 >= LMX-1)) go to 20033
  ILOW=ILOW+2
  IL1=IDLOC(ILOW,AMAT,IMAT)
20033 CONTINUE
  IPAGE=ABS(IMAT(LMX-1))
  IHI=IMAT(J+4)-(ILOW-IL1)
20036 IU1=MIN(LMX-2,IHI)
  if (.NOT.(IL1 > IU1)) go to 20038
  go to 20037
20038 CONTINUE
  DO 30 I=IL1,IU1
  WW(IMAT(I))=AMAT(I)*CSC(J)
30    CONTINUE
  if (.NOT.(IHI <= LMX-2)) go to 20041
  go to 20037
20041 CONTINUE
  IPAGE=IPAGE+1
  KEY=1
  call DPRWPG(KEY,IPAGE,LPG,AMAT,IMAT)
  IL1=NVARS+5
  IHI=IHI-LPG
  go to 20036
20037 go to 20028
20027 if (.NOT.(IND(J) == 2)) go to 20044
  WW(J-NVARS)=ONE
  go to 20045
20044 WW(J-NVARS)=-ONE
20045 CONTINUE
  CONTINUE
!
!     COMPUTE SEARCH DIRECTION.
20028 TRANS=.FALSE.
  call LA05BD(BASMAT,IBRC,LBM,MRELAS,IPR,IWR,WR,GG,WW,TRANS)
!
!     THE SEARCH DIRECTION REQUIRES THE FOLLOWING SIGN CHANGE if EITHER
!     VARIABLE ENTERING IS AT ITS UPPER BOUND OR IS FREE AND HAS
!     POSITIVE REDUCED COST.
  if (.NOT.(MOD(IBB(J),2) == 0.OR.(IND(J) == 4 .AND. RZ(J) > ZERO)) &
  ) go to 20047
  I=1
  N20050=MRELAS
  go to 20051
20050 I=I+1
20051 if ((N20050-I) < 0) go to 20052
  WW(I)=-WW(I)
  go to 20050
20052 CONTINUE
20047 DIRNRM=DASUM(MRELAS,WW,1)
!
!     COPY CONTENTS OF WR(*) TO DUALS(*) FOR USE IN
!     ADD-DROP (EXCHANGE) STEP, LA05CD( ).
  call DCOPY(MRELAS,WR,1,DUALS,1)
20024 RETURN
end
