subroutine DPLPMU (MRELAS, NVARS, LMX, LBM, NREDC, INFO, IENTER, &
     ILEAVE, IOPT, NPP, JSTRT, IBASIS, IMAT, IBRC, IPR, IWR, IND, &
     IBB, ANORM, EPS, UU, GG, RPRNRM, ERDNRM, DULNRM, THETA, COSTSC, &
     XLAMDA, RHSNRM, AMAT, BASMAT, CSC, WR, RPRIM, WW, BU, BL, RHS, &
     ERD, ERP, RZ, RG, COLNRM, COSTS, PRIMAL, DUALS, SINGLR, REDBAS, &
     ZEROLV, STPEDG)
!
!! DPLPMU is subsidiary to DSPLP.
!
!***LIBRARY   SLATEC
!***TYPE      DOUBLE PRECISION (SPLPMU-S, DPLPMU-D)
!***AUTHOR  (UNKNOWN)
!***DESCRIPTION
!
!     THE EDITING REQUIRED TO CONVERT THIS SUBROUTINE FROM SINGLE TO
!     DOUBLE PRECISION INVOLVES THE FOLLOWING CHARACTER STRING CHANGES.
!
!     USE AN EDITING COMMAND (CHANGE) /STRING-1/(TO)STRING-2/.
!     /REAL (12 BLANKS)/DOUBLE PRECISION/,
!     /SASUM/DASUM/,/SCOPY/DCOPY/,/SDOT/DDOT/,
!     /.E0/.D0/
!
!     THIS SUBPROGRAM IS FROM THE DSPLP( ) PACKAGE.  IT PERFORMS THE
!     TASKS OF UPDATING THE PRIMAL SOLUTION, EDGE WEIGHTS, REDUCED
!     COSTS, AND MATRIX DECOMPOSITION.
!     IT IS THE MAIN PART OF THE PROCEDURE (MAKE MOVE AND UPDATE).
!
!     REVISED 821122-1100
!     REVISED YYMMDD
!
!***SEE ALSO  DSPLP
!***ROUTINES CALLED  DASUM, DCOPY, DDOT, DPLPDM, DPNNZR, DPRWPG, IDLOC,
!                    LA05BD, LA05CD, XERMSG
!***REVISION HISTORY  (YYMMDD)
!   811215  DATE WRITTEN
!   890531  Changed all specific intrinsics to generic.  (WRB)
!   890605  Removed unreferenced labels.  (WRB)
!   890606  Changed references from IPLOC to IDLOC.  (WRB)
!   890606  Removed unused COMMON block LA05DD.  (WRB)
!   891214  Prologue converted to Version 4.0 format.  (BAB)
!   900315  CALLs to XERROR changed to CALLs to XERMSG.  (THJ)
!   900328  Added TYPE section.  (WRB)
!***END PROLOGUE  DPLPMU
  INTEGER IBASIS(*),IMAT(*),IBRC(LBM,2),IPR(*),IWR(*),IND(*),IBB(*)
  DOUBLE PRECISION AIJ,ALPHA,ANORM,COSTSC,ERDNRM,DULNRM,EPS,GAMMA, &
   GG,GQ,ONE,RPRNRM,RZJ,SCALR,THETA,TWO,UU,WP,XLAMDA,RHSNRM, &
   ZERO,AMAT(*),BASMAT(*),CSC(*),WR(*),RPRIM(*),WW(*),BU(*),BL(*), &
   RHS(*),ERD(*),ERP(*),RZ(*),RG(*),COSTS(*),PRIMAL(*),DUALS(*), &
   COLNRM(*),RCOST,DASUM,DDOT,CNORM
  LOGICAL SINGLR,REDBAS,PAGEPL,TRANS,ZEROLV,STPEDG
!
!***FIRST EXECUTABLE STATEMENT  DPLPMU
  ZERO=0.D0
  ONE=1.D0
  TWO=2.D0
  LPG=LMX-(NVARS+4)
!
!     UPDATE THE PRIMAL SOLUTION WITH A MULTIPLE OF THE SEARCH
!     DIRECTION.
  I=1
  N20002=MRELAS
  go to 20003
20002 I=I+1
20003 if ((N20002-I) < 0) go to 20004
  RPRIM(I)=RPRIM(I)-THETA*WW(I)
  go to 20002
!
!     if EJECTED VARIABLE IS LEAVING AT AN UPPER BOUND,  THEN
!     TRANSLATE RIGHT HAND SIDE.
20004 if (.NOT.(ILEAVE < 0)) go to 20006
  IBAS=IBASIS(ABS(ILEAVE))
  SCALR=RPRIM(ABS(ILEAVE))
  ASSIGN 20009 TO NPR001
  go to 30001
20009 IBB(IBAS)=ABS(IBB(IBAS))+1
!
!     if ENTERING VARIABLE IS RESTRICTED TO ITS UPPER BOUND, TRANSLATE
!     RIGHT HAND SIDE.  if THE VARIABLE DECREASED FROM ITS UPPER
!     BOUND, A SIGN CHANGE IS REQUIRED IN THE TRANSLATION.
20006 if (.NOT.(IENTER == ILEAVE)) go to 20010
  IBAS=IBASIS(IENTER)
  SCALR=THETA
  if (MOD(IBB(IBAS),2) == 0) SCALR=-SCALR
  ASSIGN 20013 TO NPR001
  go to 30001
20013 IBB(IBAS)=IBB(IBAS)+1
  go to 20011
20010 IBAS=IBASIS(IENTER)
!
!     if ENTERING VARIABLE IS DECREASING FROM ITS UPPER BOUND,
!     COMPLEMENT ITS PRIMAL VALUE.
  if (.NOT.(IND(IBAS) == 3.AND.MOD(IBB(IBAS),2) == 0)) go to 20014
  SCALR=-(BU(IBAS)-BL(IBAS))
  if (IBAS <= NVARS) SCALR=SCALR/CSC(IBAS)
  ASSIGN 20017 TO NPR001
  go to 30001
20017 THETA=-SCALR-THETA
  IBB(IBAS)=IBB(IBAS)+1
20014 CONTINUE
  RPRIM(ABS(ILEAVE))=THETA
  IBB(IBAS)=-ABS(IBB(IBAS))
  I=IBASIS(ABS(ILEAVE))
  IBB(I)=ABS(IBB(I))
  if ( PRIMAL(ABS(ILEAVE)+NVARS) > ZERO) IBB(I)=IBB(I)+1
!
!     INTERCHANGE COLUMN POINTERS TO NOTE EXCHANGE OF COLUMNS.
20011 IBAS=IBASIS(IENTER)
  IBASIS(IENTER)=IBASIS(ABS(ILEAVE))
  IBASIS(ABS(ILEAVE))=IBAS
!
!     if VARIABLE WAS EXCHANGED AT A ZERO LEVEL, MARK IT SO THAT
!     IT CAN'T BE BROUGHT BACK IN.  THIS IS TO HELP PREVENT CYCLING.
  if ( ZEROLV) IBASIS(IENTER)=-ABS(IBASIS(IENTER))
  RPRNRM=MAX(RPRNRM,DASUM(MRELAS,RPRIM,1))
  K=1
  N20018=MRELAS
  go to 20019
20018 K=K+1
20019 if ((N20018-K) < 0) go to 20020
!
!     SEE if VARIABLES THAT WERE CLASSIFIED AS INFEASIBLE HAVE NOW
!     BECOME FEASIBLE.  THIS MAY REQUIRED TRANSLATING UPPER BOUNDED
!     VARIABLES.
  if (.NOT.(PRIMAL(K+NVARS) /= ZERO .AND. &
            ABS(RPRIM(K)) <= RPRNRM*ERP(K))) go to 20022
  if (.NOT.(PRIMAL(K+NVARS) > ZERO)) go to 20025
  IBAS=IBASIS(K)
  SCALR=-(BU(IBAS)-BL(IBAS))
  if ( IBAS <= NVARS)SCALR=SCALR/CSC(IBAS)
  ASSIGN 20028 TO NPR001
  go to 30001
20028 RPRIM(K)=-SCALR
  RPRNRM=RPRNRM-SCALR
20025 PRIMAL(K+NVARS)=ZERO
20022 CONTINUE
  go to 20018
!
!     UPDATE REDUCED COSTS, EDGE WEIGHTS, AND MATRIX DECOMPOSITION.
20020 if (.NOT.(IENTER /= ILEAVE)) go to 20029
!
!     THE INCOMING VARIABLE IS ALWAYS CLASSIFIED AS FEASIBLE.
  PRIMAL(ABS(ILEAVE)+NVARS)=ZERO
!
  WP=WW(ABS(ILEAVE))
  GQ=DDOT(MRELAS,WW,1,WW,1)+ONE
!
!     COMPUTE INVERSE (TRANSPOSE) TIMES SEARCH DIRECTION.
  TRANS=.TRUE.
  call LA05BD(BASMAT,IBRC,LBM,MRELAS,IPR,IWR,WR,GG,WW,TRANS)
!
!     UPDATE THE MATRIX DECOMPOSITION.  COL. ABS(ILEAVE) IS LEAVING.
!     THE ARRAY DUALS(*) CONTAINS INTERMEDIATE RESULTS FOR THE
!     INCOMING COLUMN.
  call LA05CD(BASMAT,IBRC,LBM,MRELAS,IPR,IWR,DUALS,GG,UU, &
   ABS(ILEAVE))
  REDBAS=.FALSE.
  if (.NOT.(GG < ZERO)) go to 20032
!
!     REDECOMPOSE BASIS MATRIX WHEN AN ERROR RETURN FROM
!     LA05CD( ) IS NOTED.  THIS WILL PROBABLY BE DUE TO
!     SPACE BEING EXHAUSTED, GG=-7.
  call DPLPDM( &
  MRELAS,NVARS,LMX,LBM,NREDC,INFO,IOPT, &
  IBASIS,IMAT,IBRC,IPR,IWR,IND,IBB, &
  ANORM,EPS,UU,GG, &
  AMAT,BASMAT,CSC,WR, &
  SINGLR,REDBAS)
  if (.NOT.(SINGLR)) go to 20035
  NERR=26
  call XERMSG ('SLATEC', 'DPLPMU', &
     'IN DSPLP, MOVED TO A SINGULAR POINT. THIS SHOULD NOT HAPPEN.', &
     NERR, IOPT)
  INFO=-NERR
  return
20035 CONTINUE
  go to 30002
20038 CONTINUE
20032 CONTINUE
!
!     if STEEPEST EDGE PRICING IS USED, UPDATE REDUCED COSTS
!     AND EDGE WEIGHTS.
  if (.NOT.(STPEDG)) go to 20039
!
!     COMPUTE COL. ABS(ILEAVE) OF THE NEW INVERSE (TRANSPOSE) MATRIX
!     HERE ABS(ILEAVE) POINTS TO THE EJECTED COLUMN.
!     USE ERD(*) FOR TEMP. STORAGE.
  call dinit ( MRELAS,ZERO,ERD,1)
  ERD(ABS(ILEAVE))=ONE
  TRANS=.TRUE.
  call LA05BD(BASMAT,IBRC,LBM,MRELAS,IPR,IWR,WR,GG,ERD,TRANS)
!
!     COMPUTE UPDATED DUAL VARIABLES IN DUALS(*).
  ASSIGN 20042 TO NPR003
  go to 30003
!
!     COMPUTE THE DOT PRODUCT OF COL. J OF THE NEW INVERSE (TRANSPOSE)
!     WITH EACH NON-BASIC COLUMN.  ALSO COMPUTE THE DOT PRODUCT OF THE
!     INVERSE (TRANSPOSE) OF NON-UPDATED MATRIX (TIMES) THE
!     SEARCH DIRECTION WITH EACH NON-BASIC COLUMN.
!     RECOMPUTE REDUCED COSTS.
20042 PAGEPL=.TRUE.
  call dinit ( NVARS+MRELAS,ZERO,RZ,1)
  NNEGRC=0
  J=JSTRT
20043 if (.NOT.(IBB(J) <= 0)) go to 20045
  PAGEPL=.TRUE.
  RG(J)=ONE
  go to 20046
!
!     NONBASIC INDEPENDENT VARIABLES (COLUMN IN SPARSE MATRIX STORAGE)
20045 if (.NOT.(J <= NVARS)) go to 20048
  RZJ=COSTS(J)*COSTSC
  ALPHA=ZERO
  GAMMA=ZERO
!
!     COMPUTE THE DOT PRODUCT OF THE SPARSE MATRIX NONBASIC COLUMNS
!     WITH THREE VECTORS INVOLVED IN THE UPDATING STEP.
  if (.NOT.(J == 1)) go to 20051
  ILOW=NVARS+5
  go to 20052
20051 ILOW=IMAT(J+3)+1
20052 if (.NOT.(PAGEPL)) go to 20054
  IL1=IDLOC(ILOW,AMAT,IMAT)
  if (.NOT.(IL1 >= LMX-1)) go to 20057
  ILOW=ILOW+2
  IL1=IDLOC(ILOW,AMAT,IMAT)
20057 CONTINUE
  IPAGE=ABS(IMAT(LMX-1))
  go to 20055
20054 IL1=IHI+1
20055 IHI=IMAT(J+4)-(ILOW-IL1)
20060 IU1=MIN(LMX-2,IHI)
  if (.NOT.(IL1 > IU1)) go to 20062
  go to 20061
20062 CONTINUE
  DO 10 I=IL1,IU1
  RZJ=RZJ-AMAT(I)*DUALS(IMAT(I))
  ALPHA=ALPHA+AMAT(I)*ERD(IMAT(I))
  GAMMA=GAMMA+AMAT(I)*WW(IMAT(I))
10    CONTINUE
  if (.NOT.(IHI <= LMX-2)) go to 20065
  go to 20061
20065 CONTINUE
  IPAGE=IPAGE+1
  KEY=1
  call DPRWPG(KEY,IPAGE,LPG,AMAT,IMAT)
  IL1=NVARS+5
  IHI=IHI-LPG
  go to 20060
20061 PAGEPL=IHI == (LMX-2)
  RZ(J)=RZJ*CSC(J)
  ALPHA=ALPHA*CSC(J)
  GAMMA=GAMMA*CSC(J)
  RG(J)=MAX(RG(J)-TWO*ALPHA*GAMMA+ALPHA**2*GQ,ONE+ALPHA**2)
!
!     NONBASIC DEPENDENT VARIABLES (COLUMNS DEFINED IMPLICITLY)
  go to 20049
20048 PAGEPL=.TRUE.
  SCALR=-ONE
  if ( IND(J) == 2) SCALR=ONE
  I=J-NVARS
  ALPHA=SCALR*ERD(I)
  RZ(J)=-SCALR*DUALS(I)
  GAMMA=SCALR*WW(I)
  RG(J)=MAX(RG(J)-TWO*ALPHA*GAMMA+ALPHA**2*GQ,ONE+ALPHA**2)
20049 CONTINUE
20046 CONTINUE
!
  RCOST=RZ(J)
  if (MOD(IBB(J),2) == 0) RCOST=-RCOST
  if (.NOT.(IND(J) == 3)) go to 20068
  if ( BU(J) == BL(J)) RCOST=ZERO
20068 CONTINUE
  if (IND(J) == 4) RCOST=-ABS(RCOST)
  CNORM=ONE
  if (J <= NVARS) CNORM=COLNRM(J)
  if (RCOST+ERDNRM*DULNRM*CNORM < ZERO) NNEGRC=NNEGRC+1
  J=MOD(J,MRELAS+NVARS)+1
  if (.NOT.(NNEGRC >= NPP .OR. J == JSTRT)) go to 20071
  go to 20044
20071 CONTINUE
  go to 20043
20044 JSTRT=J
!
!     UPDATE THE EDGE WEIGHT FOR THE EJECTED VARIABLE.
  RG(ABS(IBASIS(IENTER)))= GQ/WP**2
!
!     if MINIMUM REDUCED COST (DANTZIG) PRICING IS USED,
!     CALCULATE THE NEW REDUCED COSTS.
  go to 20040
!
!     COMPUTE THE UPDATED DUALS IN DUALS(*).
20039 ASSIGN 20074 TO NPR003
  go to 30003
20074 call dinit ( NVARS+MRELAS,ZERO,RZ,1)
  NNEGRC=0
  J=JSTRT
  PAGEPL=.TRUE.
!
20075 if (.NOT.(IBB(J) <= 0)) go to 20077
  PAGEPL=.TRUE.
  go to 20078
!
!     NONBASIC INDEPENDENT VARIABLE (COLUMN IN SPARSE MATRIX STORAGE)
20077 if (.NOT.(J <= NVARS)) go to 20080
  RZ(J)=COSTS(J)*COSTSC
  if (.NOT.(J == 1)) go to 20083
  ILOW=NVARS+5
  go to 20084
20083 ILOW=IMAT(J+3)+1
20084 CONTINUE
  if (.NOT.(PAGEPL)) go to 20086
  IL1=IDLOC(ILOW,AMAT,IMAT)
  if (.NOT.(IL1 >= LMX-1)) go to 20089
  ILOW=ILOW+2
  IL1=IDLOC(ILOW,AMAT,IMAT)
20089 CONTINUE
  IPAGE=ABS(IMAT(LMX-1))
  go to 20087
20086 IL1=IHI+1
20087 CONTINUE
  IHI=IMAT(J+4)-(ILOW-IL1)
20092 IU1=MIN(LMX-2,IHI)
  if (.NOT.(IU1 >= IL1 .AND.MOD(IU1-IL1,2) == 0)) go to 20094
  RZ(J)=RZ(J)-AMAT(IL1)*DUALS(IMAT(IL1))
  IL1=IL1+1
20094 CONTINUE
  if (.NOT.(IL1 > IU1)) go to 20097
  go to 20093
20097 CONTINUE
!
!     UNROLL THE DOT PRODUCT LOOP TO A DEPTH OF TWO.  (THIS IS DONE
!     FOR INCREASED EFFICIENCY).
  DO 40 I=IL1,IU1,2
  RZ(J)=RZ(J)-AMAT(I)*DUALS(IMAT(I))-AMAT(I+1)*DUALS(IMAT(I+1))
40    CONTINUE
  if (.NOT.(IHI <= LMX-2)) go to 20100
  go to 20093
20100 CONTINUE
  IPAGE=IPAGE+1
  KEY=1
  call DPRWPG(KEY,IPAGE,LPG,AMAT,IMAT)
  IL1=NVARS+5
  IHI=IHI-LPG
  go to 20092
20093 PAGEPL=IHI == (LMX-2)
  RZ(J)=RZ(J)*CSC(J)
!
!     NONBASIC DEPENDENT VARIABLES (COLUMNS DEFINED IMPLICITLY)
  go to 20081
20080 PAGEPL=.TRUE.
  SCALR=-ONE
  if ( IND(J) == 2) SCALR=ONE
  I=J-NVARS
  RZ(J)=-SCALR*DUALS(I)
20081 CONTINUE
20078 CONTINUE
!
  RCOST=RZ(J)
  if (MOD(IBB(J),2) == 0) RCOST=-RCOST
  if (.NOT.(IND(J) == 3)) go to 20103
  if ( BU(J) == BL(J)) RCOST=ZERO
20103 CONTINUE
  if (IND(J) == 4) RCOST=-ABS(RCOST)
  CNORM=ONE
  if (J <= NVARS) CNORM=COLNRM(J)
  if (RCOST+ERDNRM*DULNRM*CNORM < ZERO) NNEGRC=NNEGRC+1
  J=MOD(J,MRELAS+NVARS)+1
  if (.NOT.(NNEGRC >= NPP .OR. J == JSTRT)) go to 20106
  go to 20076
20106 CONTINUE
  go to 20075
20076 JSTRT=J
20040 CONTINUE
  go to 20030
!
!     THIS IS NECESSARY ONLY FOR PRINTING OF INTERMEDIATE RESULTS.
20029 ASSIGN 20109 TO NPR003
  go to 30003
20109 CONTINUE
20030 RETURN
!     PROCEDURE (TRANSLATE RIGHT HAND SIDE)
!
!     PERFORM THE TRANSLATION ON THE RIGHT-HAND SIDE.
30001 if (.NOT.(IBAS <= NVARS)) go to 20110
  I=0
20113 call DPNNZR(I,AIJ,IPLACE,AMAT,IMAT,IBAS)
  if (.NOT.(I <= 0)) go to 20115
  go to 20114
20115 CONTINUE
  RHS(I)=RHS(I)-SCALR*AIJ*CSC(IBAS)
  go to 20113
20114 go to 20111
20110 I=IBAS-NVARS
  if (.NOT.(IND(IBAS) == 2)) go to 20118
  RHS(I)=RHS(I)-SCALR
  go to 20119
20118 RHS(I)=RHS(I)+SCALR
20119 CONTINUE
20111 CONTINUE
  RHSNRM=MAX(RHSNRM,DASUM(MRELAS,RHS,1))
  go to NPR001, (20009,20013,20017,20028)
!     PROCEDURE (COMPUTE NEW PRIMAL)
!
!     COPY RHS INTO WW(*), SOLVE SYSTEM.
30002 call DCOPY(MRELAS,RHS,1,WW,1)
  TRANS = .FALSE.
  call LA05BD(BASMAT,IBRC,LBM,MRELAS,IPR,IWR,WR,GG,WW,TRANS)
  call DCOPY(MRELAS,WW,1,RPRIM,1)
  RPRNRM=DASUM(MRELAS,RPRIM,1)
  go to 20038
!     PROCEDURE (COMPUTE NEW DUALS)
!
!     SOLVE FOR DUAL VARIABLES. FIRST COPY COSTS INTO DUALS(*).
30003 I=1
  N20121=MRELAS
  go to 20122
20121 I=I+1
20122 if ((N20121-I) < 0) go to 20123
  J=IBASIS(I)
  if (.NOT.(J <= NVARS)) go to 20125
  DUALS(I)=COSTSC*COSTS(J)*CSC(J) + XLAMDA*PRIMAL(I+NVARS)
  go to 20126
20125 DUALS(I)=XLAMDA*PRIMAL(I+NVARS)
20126 CONTINUE
  go to 20121
!
20123 TRANS=.TRUE.
  call LA05BD(BASMAT,IBRC,LBM,MRELAS,IPR,IWR,WR,GG,DUALS,TRANS)
  DULNRM=DASUM(MRELAS,DUALS,1)
  go to NPR003, (20042,20074,20109)
end
