subroutine DPRWVR (KEY, IPAGE, LPG, SX, IX)
!
!! DPRWVR is subsidiary to DSPLP.
!
!***LIBRARY   SLATEC
!***TYPE      DOUBLE PRECISION (PRWVIR-S, DPRWVR-D)
!***AUTHOR  Hanson, R. J., (SNLA)
!           Wisniewski, J. A., (SNLA)
!***DESCRIPTION
!
!     DPRWVR LIMITS THE TYPE OF STORAGE TO A SEQUENTIAL SPARSE MATRIX
!     STORAGE SCHEME.  THE PAGE STORAGE IS ON RANDOM ACCESS DISK.
!     DPRWVR IS PART OF THE SPARSE LP PACKAGE, DSPLP.
!
!     KEY       IS A FLAG WHICH INDICATES WHETHER A READ OR WRITE
!               OPERATION IS TO BE PERFORMED. A VALUE OF KEY=1 INDICATES
!               A READ. A VALUE OF KEY=2 INDICATES A WRITE.
!     IPAGE     IS THE PAGE OF MATRIX MN WE ARE ACCESSING.
!     LPG       IS THE LENGTH OF THE PAGE.
!   SX(*),IX(*) IS THE MATRIX DATA.
!
!     THIS SUBROUTINE IS A MODIFICATION OF THE SUBROUTINE LRWVIR,
!     SANDIA LABS. REPT. SAND78-0785.
!     MODIFICATIONS BY K.L. HIEBERT AND R.J. HANSON
!
!***SEE ALSO  DSPLP
!***ROUTINES CALLED  DREADP, DWRITP, SOPENM
!***REVISION HISTORY  (YYMMDD)
!   811215  DATE WRITTEN
!   891009  Removed unreferenced variables.  (WRB)
!   891214  Prologue converted to Version 4.0 format.  (BAB)
!   900328  Added TYPE section.  (WRB)
!   910403  Updated AUTHOR and DESCRIPTION sections.  (WRB)
!***END PROLOGUE  DPRWVR
  DIMENSION IX(*)
  DOUBLE PRECISION SX(*),ZERO,ONE
  LOGICAL FIRST
  SAVE ZERO, ONE
  DATA ZERO,ONE/0.D0,1.D0/
!***FIRST EXECUTABLE STATEMENT  DPRWVR
!
!     COMPUTE STARTING ADDRESS OF PAGE.
!
  IPAGEF=SX(3)
  ISTART = IX(3) + 5
!
!     OPEN RANDOM ACCESS FILE NUMBER IPAGEF, if FIRST PAGE WRITE.
!
  FIRST=SX(4) == ZERO
  if (.NOT.(FIRST)) go to 20002
  call SOPENM(IPAGEF,LPG)
  SX(4)=ONE
!
!     PERFORM EITHER A READ OR A WRITE.
!
20002 IADDR = 2*IPAGE - 1
  if (.NOT.(KEY == 1)) go to 20005
  call DREADP(IPAGEF,IX(ISTART),SX(ISTART),LPG,IADDR)
  go to 20006
20005 if (.NOT.(KEY == 2)) go to 10001
  call DWRITP(IPAGEF,IX(ISTART),SX(ISTART),LPG,IADDR)
10001 CONTINUE
20006 RETURN
end
