subroutine DREADP (IPAGE, LIST, RLIST, LPAGE, IREC)
!
!! DREADP reads a record from a file, for DSPLP.
!
!***SUBSIDIARY
!***PURPOSE  Subsidiary to DSPLP
!***LIBRARY   SLATEC
!***TYPE      DOUBLE PRECISION (SREADP-S, DREADP-D)
!***AUTHOR  (UNKNOWN)
!***DESCRIPTION
!
!     READ RECORD NUMBER IRECN, OF LENGTH LPG, FROM UNIT
!     NUMBER IPAGEF INTO THE STORAGE ARRAY, LIST(*).
!     READ RECORD  IRECN+1, OF LENGTH LPG, FROM UNIT NUMBER
!     IPAGEF INTO THE STORAGE ARRAY RLIST(*).
!
!     TO CONVERT THIS PROGRAM UNIT TO DOUBLE PRECISION CHANGE
!     /REAL (12 BLANKS)/ TO /DOUBLE PRECISION/.
!
!***SEE ALSO  DSPLP
!***ROUTINES CALLED  XERMSG
!***REVISION HISTORY  (YYMMDD)
!   811215  DATE WRITTEN
!   890605  Corrected references to XERRWV.  (WRB)
!   891214  Prologue converted to Version 4.0 format.  (BAB)
!   900328  Added TYPE section.  (WRB)
!   900510  Convert XERRWV calls to XERMSG calls.  (RWC)
!***END PROLOGUE  DREADP
  INTEGER LIST(*)
  DOUBLE PRECISION RLIST(*)
  CHARACTER*8 XERN1, XERN2
!***FIRST EXECUTABLE STATEMENT  DREADP
  IPAGEF=IPAGE
  LPG   =LPAGE
  IRECN=IREC
  READ(IPAGEF,REC=IRECN,ERR=100)(LIST(I),I=1,LPG)
  READ(IPAGEF,REC=IRECN+1,ERR=100)(RLIST(I),I=1,LPG)
  return
!
  100 WRITE (XERN1, '(I8)') LPG
  WRITE (XERN2, '(I8)') IRECN
  call XERMSG ('SLATEC', 'DREADP', 'IN DSPLP, LPG = ' // XERN1 // &
     ' IRECN = ' // XERN2, 100, 1)
  return
end
