subroutine DVOUT (N, DX, IFMT, IDIGIT)
!
!! DVOUT prints a double precision vector.
!
!***SUBSIDIARY
!***PURPOSE  Subsidiary to DSPLP
!***LIBRARY   SLATEC
!***TYPE      DOUBLE PRECISION (SVOUT-S, DVOUT-D)
!***AUTHOR  Hanson, R. J., (SNLA)
!           Wisniewski, J. A., (SNLA)
!***DESCRIPTION
!
!     DOUBLE PRECISION VECTOR OUTPUT ROUTINE.
!
!  INPUT..
!
!  N,DX(*) PRINT THE DOUBLE PRECISION ARRAY DX(I),I=1,...,N, ON
!          OUTPUT UNIT LOUT. THE HEADING IN THE FORTRAN FORMAT
!          STATEMENT IFMT(*), DESCRIBED BELOW, IS PRINTED AS A FIRST
!          STEP. THE COMPONENTS DX(I) ARE INDEXED, ON OUTPUT,
!          IN A PLEASANT FORMAT.
!  IFMT(*) A FORTRAN FORMAT STATEMENT. THIS IS PRINTED ON OUTPUT
!          UNIT LOUT WITH THE VARIABLE FORMAT FORTRAN STATEMENT
!                WRITE(LOUT,IFMT)
!  IDIGIT  PRINT AT LEAST ABS(IDIGIT) DECIMAL DIGITS PER NUMBER.
!          THE SUBPROGRAM WILL CHOOSE THAT INTEGER 4,6,10 OR 14
!          WHICH WILL PRINT AT LEAST ABS(IDIGIT) NUMBER OF
!          PLACES.  if IDIGIT < 0, 72 PRINTING COLUMNS ARE UTILIZED
!          TO WRITE EACH LINE OF OUTPUT OF THE ARRAY DX(*). (THIS
!          CAN BE USED ON MOST TIME-SHARING TERMINALS). IF
!          IDIGIT >= 0, 133 PRINTING COLUMNS ARE UTILIZED. (THIS CAN
!          BE USED ON MOST LINE PRINTERS).
!
!  EXAMPLE..
!
!  PRINT AN ARRAY CALLED (COSTS OF PURCHASES) OF LENGTH 100 SHOWING
!  6 DECIMAL DIGITS PER NUMBER. THE USER IS RUNNING ON A TIME-SHARING
!  SYSTEM WITH A 72 COLUMN OUTPUT DEVICE.
!
!     DOUBLE PRECISION COSTS(100)
!     N = 100
!     IDIGIT = -6
!     call DVOUT(N,COSTS,'(''1COSTS OF PURCHASES'')',IDIGIT)
!
!***SEE ALSO  DSPLP
!***ROUTINES CALLED  I1MACH
!***REVISION HISTORY  (YYMMDD)
!   811215  DATE WRITTEN
!   890531  Changed all specific intrinsics to generic.  (WRB)
!   891107  Added comma after 1P edit descriptor in FORMAT
!           statements.  (WRB)
!   891214  Prologue converted to Version 4.0 format.  (BAB)
!   900328  Added TYPE section.  (WRB)
!   910403  Updated AUTHOR section.  (WRB)
!***END PROLOGUE  DVOUT
  IMPLICIT DOUBLE PRECISION (A-H,O-Z)
  DOUBLE PRECISION DX(*)
  CHARACTER IFMT*(*)
!***FIRST EXECUTABLE STATEMENT  DVOUT
  LOUT=I1MACH(2)
  WRITE(LOUT,IFMT)
  if ( N <= 0) RETURN
  NDIGIT = IDIGIT
  if ( IDIGIT == 0) NDIGIT = 6
  if ( IDIGIT >= 0) go to 80
!
  NDIGIT = -IDIGIT
  if ( NDIGIT > 6) go to 20
!
  DO 10 K1=1,N,4
  K2 = MIN(N,K1+3)
  WRITE(LOUT,1000) K1,K2,(DX(I),I = K1, K2)
   10 CONTINUE
  return
!
   20 CONTINUE
  if ( NDIGIT > 14) go to 40
!
  DO 30 K1=1,N,2
  K2 = MIN(N,K1+1)
  WRITE(LOUT,1001) K1,K2,(DX(I),I = K1, K2)
   30 CONTINUE
  return
!
   40 CONTINUE
  if ( NDIGIT > 20) go to 60
!
  DO 50 K1=1,N,2
  K2=MIN(N,K1+1)
  WRITE(LOUT,1002) K1,K2,(DX(I),I = K1, K2)
   50 CONTINUE
  return
!
   60 CONTINUE
  DO 70 K1=1,N
  K2 = K1
  WRITE(LOUT,1003) K1,K2,(DX(I),I = K1, K2)
   70 CONTINUE
  return
!
   80 CONTINUE
  if ( NDIGIT > 6) go to 100
!
  DO 90 K1=1,N,8
  K2 = MIN(N,K1+7)
  WRITE(LOUT,1000) K1,K2,(DX(I),I = K1, K2)
   90 CONTINUE
  return
!
  100 CONTINUE
  if ( NDIGIT > 14) go to 120
!
  DO 110 K1=1,N,5
  K2 = MIN(N,K1+4)
  WRITE(LOUT,1001) K1,K2,(DX(I),I = K1, K2)
  110 CONTINUE
  return
!
  120 CONTINUE
  if ( NDIGIT > 20) go to 140
!
  DO 130 K1=1,N,4
  K2 = MIN(N,K1+3)
  WRITE(LOUT,1002) K1,K2,(DX(I),I = K1, K2)
  130 CONTINUE
  return
!
  140 CONTINUE
  DO 150 K1=1,N,3
  K2 = MIN(N,K1+2)
  WRITE(LOUT,1003) K1,K2,(DX(I),I = K1, K2)
  150 CONTINUE
  return
 1000 FORMAT(1X,I4,3H - ,I4,1X,1P,8D14.5)
 1001 FORMAT(1X,I4,3H - ,I4,1X,1P,5D22.13)
 1002 FORMAT(1X,I4,3H - ,I4,1X,1P,4D28.19)
 1003 FORMAT(1X,I4,3H - ,I4,1X,1P,3D36.27)
end
