subroutine DWRITP (IPAGE, LIST, RLIST, LPAGE, IREC)
!
!! DWRITP is subsidiary to DSPLP.
!
!***LIBRARY   SLATEC
!***TYPE      DOUBLE PRECISION (SWRITP-S, DWRITP-D)
!***AUTHOR  (UNKNOWN)
!***DESCRIPTION
!
!     WRITE RECORD NUMBER IRECN, OF LENGTH LPG, FROM STORAGE
!     ARRAY LIST(*) ONTO UNIT NUMBER IPAGEF.
!     WRITE RECORD NUMBER IRECN+1, OF LENGTH LPG, ONTO UNIT
!     NUMBER IPAGEF FROM THE STORAGE ARRAY RLIST(*).
!
!     TO CHANGE THIS PROGRAM UNIT TO DOUBLE PRECISION CHANGE
!     /REAL (12 BLANKS)/ TO /DOUBLE PRECISION/.
!
!***SEE ALSO  DSPLP
!***ROUTINES CALLED  XERMSG
!***REVISION HISTORY  (YYMMDD)
!   811215  DATE WRITTEN
!   890605  Corrected references to XERRWV.  (WRB)
!   891214  Prologue converted to Version 4.0 format.  (BAB)
!   900328  Added TYPE section.  (WRB)
!   900510  Convert XERRWV calls to XERMSG calls.  (RWC)
!***END PROLOGUE  DWRITP
  INTEGER LIST(*)
  DOUBLE PRECISION RLIST(*)
  CHARACTER*8 XERN1, XERN2
!***FIRST EXECUTABLE STATEMENT  DWRITP
  IPAGEF=IPAGE
  LPG   =LPAGE
  IRECN =IREC
  WRITE(IPAGEF,REC=IRECN,ERR=100)(LIST(I),I=1,LPG)
  WRITE(IPAGEF,REC=IRECN+1,ERR=100)(RLIST(I),I=1,LPG)
  return
!
  100 WRITE (XERN1, '(I8)') LPG
  WRITE (XERN2, '(I8)') IRECN
  call XERMSG ('SLATEC', 'DWRITP', 'IN DSPLP, LGP = ' // XERN1 // &
     ' IRECN = ' // XERN2, 100, 1)
  return
end
