subroutine IVOUT (N, IX, IFMT, IDIGIT)
!
!! IVOUT prints an integer vector.
!
!***LIBRARY   SLATEC
!***TYPE      INTEGER (IVOUT-I)
!***AUTHOR  Hanson, R. J., (SNLA)
!           Wisniewski, J. A., (SNLA)
!***DESCRIPTION
!
!     INTEGER VECTOR OUTPUT ROUTINE.
!
!  INPUT..
!
!  N,IX(*) PRINT THE INTEGER ARRAY IX(I),I=1,...,N, ON OUTPUT
!          UNIT LOUT. THE HEADING IN THE FORTRAN FORMAT
!          STATEMENT IFMT(*), DESCRIBED BELOW, IS PRINTED AS A FIRST
!          STEP. THE COMPONENTS IX(I) ARE INDEXED, ON OUTPUT,
!          IN A PLEASANT FORMAT.
!  IFMT(*) A FORTRAN FORMAT STATEMENT. THIS IS PRINTED ON OUTPUT
!          UNIT LOUT WITH THE VARIABLE FORMAT FORTRAN STATEMENT
!                WRITE(LOUT,IFMT)
!  IDIGIT  PRINT UP TO ABS(IDIGIT) DECIMAL DIGITS PER NUMBER.
!          THE SUBPROGRAM WILL CHOOSE THAT INTEGER 4,6,10 OR 14
!          WHICH WILL PRINT AT LEAST ABS(IDIGIT) NUMBER OF
!          PLACES.  if IDIGIT < 0, 72 PRINTING COLUMNS ARE UTILIZED
!          TO WRITE EACH LINE OF OUTPUT OF THE ARRAY IX(*). (THIS
!          CAN BE USED ON MOST TIME-SHARING TERMINALS). IF
!          IDIGIT >= 0, 133 PRINTING COLUMNS ARE UTILIZED. (THIS CAN
!          BE USED ON MOST LINE PRINTERS).
!
!  EXAMPLE..
!
!  PRINT AN ARRAY CALLED (COSTS OF PURCHASES) OF LENGTH 100 SHOWING
!  6 DECIMAL DIGITS PER NUMBER. THE USER IS RUNNING ON A TIME-SHARING
!  SYSTEM WITH A 72 COLUMN OUTPUT DEVICE.
!
!     DIMENSION ICOSTS(100)
!     N = 100
!     IDIGIT = -6
!     call IVOUT(N,ICOSTS,'(''1COSTS OF PURCHASES'')',IDIGIT)
!
!***SEE ALSO  SPLP
!***ROUTINES CALLED  I1MACH
!***REVISION HISTORY  (YYMMDD)
!   811215  DATE WRITTEN
!   890531  Changed all specific intrinsics to generic.  (WRB)
!   891214  Prologue converted to Version 4.0 format.  (BAB)
!   900402  Added TYPE section.  (WRB)
!   910403  Updated AUTHOR section.  (WRB)
!***END PROLOGUE  IVOUT
  DIMENSION IX(*)
  CHARACTER IFMT*(*)
!
!     GET THE UNIT NUMBER WHERE OUTPUT WILL BE WRITTEN.
!***FIRST EXECUTABLE STATEMENT  IVOUT
  J=2
  LOUT=I1MACH(J)
  WRITE(LOUT,IFMT)
  if ( N <= 0) RETURN
  NDIGIT = IDIGIT
  if ( IDIGIT == 0) NDIGIT = 4
  if ( IDIGIT >= 0) go to 80
!
  NDIGIT = -IDIGIT
  if ( NDIGIT > 4) go to 20
!
  DO 10 K1=1,N,10
  K2 = MIN(N,K1+9)
  WRITE(LOUT,1000) K1,K2,(IX(I),I=K1,K2)
   10 CONTINUE
  return
!
   20 CONTINUE
  if ( NDIGIT > 6) go to 40
!
  DO 30 K1=1,N,7
  K2 = MIN(N,K1+6)
  WRITE(LOUT,1001) K1,K2,(IX(I),I=K1,K2)
   30 CONTINUE
  return
!
   40 CONTINUE
  if ( NDIGIT > 10) go to 60
!
  DO 50 K1=1,N,5
  K2=MIN(N,K1+4)
  WRITE(LOUT,1002) K1,K2,(IX(I),I=K1,K2)
   50 CONTINUE
  return
!
   60 CONTINUE
  DO 70 K1=1,N,3
  K2 = MIN(N,K1+2)
  WRITE(LOUT,1003) K1,K2,(IX(I),I=K1,K2)
   70 CONTINUE
  return
!
   80 CONTINUE
  if ( NDIGIT > 4) go to 100
!
  DO 90 K1=1,N,20
  K2 = MIN(N,K1+19)
  WRITE(LOUT,1000) K1,K2,(IX(I),I=K1,K2)
   90 CONTINUE
  return
!
  100 CONTINUE
  if ( NDIGIT > 6) go to 120
!
  DO 110 K1=1,N,15
  K2 = MIN(N,K1+14)
  WRITE(LOUT,1001) K1,K2,(IX(I),I=K1,K2)
  110 CONTINUE
  return
!
  120 CONTINUE
  if ( NDIGIT > 10) go to 140
!
  DO 130 K1=1,N,10
  K2 = MIN(N,K1+9)
  WRITE(LOUT,1002) K1,K2,(IX(I),I=K1,K2)
  130 CONTINUE
  return
!
  140 CONTINUE
  DO 150 K1=1,N,7
  K2 = MIN(N,K1+6)
  WRITE(LOUT,1003) K1,K2,(IX(I),I=K1,K2)
  150 CONTINUE
  return
 1000 FORMAT(1X,I4,' - ',I4,20(1X,I5))
 1001 FORMAT(1X,I4,' - ',I4,15(1X,I7))
 1002 FORMAT(1X,I4,' - ',I4,10(1X,I11))
 1003 FORMAT(1X,I4,' - ',I4,7(1X,I15))
end
