subroutine PCHNGS (II, XVAL, IPLACE, SX, IX, IRCX)
!
!! PCHNGS is subsidiary to SPLP.
!
!***LIBRARY   SLATEC
!***TYPE      SINGLE PRECISION (PCHNGS-S, DPCHNG-D)
!***AUTHOR  Hanson, R. J., (SNLA)
!           Wisniewski, J. A., (SNLA)
!***DESCRIPTION
!
!     PCHNGS LIMITS THE TYPE OF STORAGE TO A SEQUENTIAL SCHEME.
!     SPARSE MATRIX ELEMENT ALTERATION SUBROUTINE.
!
!     SUBROUTINE PCHNGS() CHANGES ELEMENT II IN VECTOR +/- IRCX TO THE
!     VALUE XVAL.
!
!            II THE ABSOLUTE VALUE OF THIS INTEGER IS THE SUBSCRIPT FOR
!               THE ELEMENT TO BE CHANGED.
!          XVAL NEW VALUE OF THE MATRIX ELEMENT BEING CHANGED.
!     IPLACE POINTER INFORMATION WHICH IS MAINTAINED BY THE PACKAGE.
!   SX(*),IX(*) THE WORK ARRAYS WHICH ARE USED TO STORE THE SPARSE
!               MATRIX. THESE ARRAYS ARE AUTOMATICALLY MAINTAINED BY THE
!               PACKAGE FOR THE USER.
!          IRCX POINTS TO THE VECTOR OF THE MATRIX BEING UPDATED.
!               A NEGATIVE VALUE OF IRCX INDICATES THAT ROW -IRCX IS
!               BEING UPDATED.  A POSITIVE VALUE OF IRCX INDICATES THAT
!               COLUMN IRCX IS BEING UPDATED.  A ZERO VALUE OF IRCX IS
!               AN ERROR.
!
!     SINCE DATA ITEMS ARE KEPT SORTED IN THE SEQUENTIAL DATA STRUCTURE,
!     CHANGING A MATRIX ELEMENT CAN REQUIRE THE MOVEMENT OF ALL THE DATA
!     ITEMS IN THE MATRIX. FOR THIS REASON, IT IS SUGGESTED THAT DATA
!     ITEMS BE ADDED A COL. AT A TIME, IN ASCENDING COL. SEQUENCE.
!     FURTHERMORE, SINCE DELETING ITEMS FROM THE DATA STRUCTURE MAY ALSO
!     REQUIRE MOVING LARGE AMOUNTS OF DATA, ZERO ELEMENTS ARE EXPLICITLY
!     STORED IN THE MATRIX.
!
!     THIS SUBROUTINE IS A MODIFICATION OF THE SUBROUTINE LCHNGS,
!     SANDIA LABS. REPT. SAND78-0785.
!     MODIFICATIONS BY K.L. HIEBERT AND R.J. HANSON
!     REVISED 811130-1000
!     REVISED YYMMDD-HHMM
!
!***SEE ALSO  SPLP
!***ROUTINES CALLED  IPLOC, PRWPGE, XERMSG
!***REVISION HISTORY  (YYMMDD)
!   811215  DATE WRITTEN
!   890531  Changed all specific intrinsics to generic.  (WRB)
!   891214  Prologue converted to Version 4.0 format.  (BAB)
!   900315  CALLs to XERROR changed to CALLs to XERMSG.  (THJ)
!   900328  Added TYPE section.  (WRB)
!   910403  Updated AUTHOR and DESCRIPTION sections.  (WRB)
!***END PROLOGUE  PCHNGS
  DIMENSION IX(*)
  INTEGER IPLOC
  REAL SX(*),XVAL,ZERO,ONE,SXLAST,SXVAL
  SAVE ZERO, ONE
  DATA ZERO,ONE /0.E0,1.E0/
!***FIRST EXECUTABLE STATEMENT  PCHNGS
  IOPT=1
!
!     DETERMINE NULL-CASES..
  if ( II == 0) RETURN
!
!     CHECK VALIDITY OF ROW/COL. INDEX.
!
  if (.NOT.(IRCX == 0)) go to 20002
  NERR=55
  call XERMSG ('SLATEC', 'PCHNGS', 'IRCX=0.', NERR, IOPT)
20002 LMX = IX(1)
!
!     LMX IS THE LENGTH OF THE IN-MEMORY STORAGE AREA.
!
  if (.NOT.(IRCX < 0)) go to 20005
!
!     CHECK SUBSCRIPTS OF THE ROW. THE ROW NUMBER MUST BE  <=  M AND
!     THE INDEX MUST BE  <=  N.
!
  if (.NOT.(IX(2) < -IRCX .OR. IX(3) < ABS(II))) go to 20008
  NERR=55
  call XERMSG ('SLATEC', 'PCHNGS', &
     'SUBSCRIPTS FOR ARRAY ELEMENT TO BE ACCESSED WERE OUT OF ' // &
     'BOUNDS.', NERR, IOPT)
20008 go to 20006
!
!     CHECK SUBSCRIPTS OF THE COLUMN. THE COL. NUMBER MUST BE  <=  N AND
!     THE INDEX MUST BE  <=  M.
!
20005 if (.NOT.(IX(3) < IRCX .OR. IX(2) < ABS(II))) go to 20011
  NERR=55
  call XERMSG ('SLATEC', 'PCHNGS', &
     'SUBSCRIPTS FOR ARRAY ELEMENT TO BE ACCESSED WERE OUT OF ' // &
     'BOUNDS.', NERR, IOPT)
20011 CONTINUE
!
!     SET I TO BE THE ELEMENT OF ROW/COLUMN J TO BE CHANGED.
!
20006 if (.NOT.(IRCX > 0)) go to 20014
  I = ABS(II)
  J = ABS(IRCX)
  go to 20015
20014 I = ABS(IRCX)
  J = ABS(II)
!
!     THE INTEGER LL POINTS TO THE START OF THE MATRIX ELEMENT DATA.
!
20015 LL=IX(3)+4
  II = ABS(II)
  LPG = LMX - LL
!
!     SET IPLACE TO START OUR SCAN FOR THE ELEMENT AT THE BEGINNING
!     OF THE VECTOR.
!
  if (.NOT.(J == 1)) go to 20017
  IPLACE=LL+1
  go to 20018
20017 IPLACE=IX(J+3)+1
!
!     IEND POINTS TO THE LAST ELEMENT OF THE VECTOR TO BE SCANNED.
!
20018 IEND = IX(J+4)
!
!     SCAN THROUGH SEVERAL PAGES, if NECESSARY, TO FIND MATRIX ELEMENT.
!
  IPL = IPLOC(IPLACE,SX,IX)
  NP = ABS(IX(LMX-1))
  go to 20021
20020 if (ILAST == IEND) go to 20022
!
!     THE VIRTUAL END OF DATA FOR THIS PAGE IS ILAST.
!
20021 ILAST = MIN(IEND,NP*LPG+LL-2)
!
!     THE RELATIVE END OF DATA FOR THIS PAGE IS IL.
!     SEARCH FOR A MATRIX VALUE WITH AN INDEX  >=  I ON THE PRESENT
!     PAGE.
!
  IL = IPLOC(ILAST,SX,IX)
  IL = MIN(IL,LMX-2)
20023 if (.NOT.(.NOT.(IPL >= IL .OR. IX(IPL) >= I))) go to 20024
  IPL=IPL+1
  go to 20023
!
!     SET IPLACE AND STORE DATA ITEM if FOUND.
!
20024 if (.NOT.(IX(IPL) == I .AND. IPL <= IL)) go to 20025
  SX(IPL) = XVAL
  SX(LMX) = ONE
  return
!
!     EXIT FROM LOOP if ITEM WAS FOUND.
!
20025 if ( IX(IPL) > I .AND. IPL <= IL) ILAST = IEND
  if (.NOT.(ILAST /= IEND)) go to 20028
  IPL = LL + 1
  NP = NP + 1
20028 go to 20020
!
!     INSERT NEW DATA ITEM INTO LOCATION AT IPLACE(IPL).
!
20022 if (.NOT.(IPL > IL.OR.(IPL == IL.AND.I > IX(IPL)))) go to 20031
  IPL = IL + 1
  if ( IPL == LMX-1) IPL = IPL + 2
20031 IPLACE = (NP-1)*LPG + IPL
!
!     go to A NEW PAGE, if NECESSARY, TO INSERT THE ITEM.
!
  if (.NOT.(IPL <= LMX .OR. IX(LMX-1) >= 0)) go to 20034
  IPL=IPLOC(IPLACE,SX,IX)
20034 IEND = IX(LL)
  NP = ABS(IX(LMX-1))
  SXVAL = XVAL
!
!     LOOP THROUGH ALL SUBSEQUENT PAGES OF THE MATRIX MOVING DATA DOWN.
!     THIS IS NECESSARY TO MAKE ROOM FOR THE NEW MATRIX ELEMENT AND
!     KEEP THE ENTRIES SORTED.
!
  go to 20038
20037 if (IX(LMX-1) <= 0) go to 20039
20038 ILAST = MIN(IEND,NP*LPG+LL-2)
  IL = IPLOC(ILAST,SX,IX)
  IL = MIN(IL,LMX-2)
  SXLAST = SX(IL)
  IXLAST = IX(IL)
  ISTART = IPL + 1
  if (.NOT.(ISTART <= IL)) go to 20040
  K = ISTART + IL
  DO 50 JJ=ISTART,IL
  SX(K-JJ) = SX(K-JJ-1)
  IX(K-JJ) = IX(K-JJ-1)
50    CONTINUE
  SX(LMX) = ONE
20040 if (.NOT.(IPL <= LMX)) go to 20043
  SX(IPL) = SXVAL
  IX(IPL) = I
  SXVAL = SXLAST
  I = IXLAST
  SX(LMX) = ONE
  if (.NOT.(IX(LMX-1) > 0)) go to 20046
  IPL = LL + 1
  NP = NP + 1
20046 CONTINUE
20043 go to 20037
20039 NP = ABS(IX(LMX-1))
!
!     DETERMINE if A NEW PAGE IS TO BE CREATED FOR THE LAST ELEMENT
!     MOVED DOWN.
!
  IL = IL + 1
  if (.NOT.(IL == LMX-1)) go to 20049
!
!     CREATE A NEW PAGE.
!
  IX(LMX-1) = NP
!
!     WRITE THE OLD PAGE.
!
  SX(LMX) = ZERO
  KEY = 2
  call PRWPGE(KEY,NP,LPG,SX,IX)
  SX(LMX) = ONE
!
!     STORE LAST ELEMENT MOVED DOWN IN A NEW PAGE.
!
  IPL = LL + 1
  NP = NP + 1
  IX(LMX-1) = -NP
  SX(IPL) = SXVAL
  IX(IPL) = I
  go to 20050
!
!     LAST ELEMENT MOVED REMAINED ON THE OLD PAGE.
!
20049 if (.NOT.(IPL /= IL)) go to 20052
  SX(IL) = SXVAL
  IX(IL) = I
  SX(LMX) = ONE
20052 CONTINUE
!
!     INCREMENT POINTERS TO LAST ELEMENT IN VECTORS J,J+1,... .
!
20050 JSTART = J + 4
  JJ=JSTART
  N20055=LL
  go to 20056
20055 JJ=JJ+1
20056 if ((N20055-JJ) < 0) go to 20057
  IX(JJ) = IX(JJ) + 1
  if ( MOD(IX(JJ)-LL,LPG) == LPG-1) IX(JJ) = IX(JJ) + 2
  go to 20055
!
!     IPLACE POINTS TO THE INSERTED DATA ITEM.
!
20057 IPL=IPLOC(IPLACE,SX,IX)
  return
end
