subroutine PINITM (M, N, SX, IX, LMX, IPAGEF)
!
!! PINITM is subsidiary to SPLP.
!
!***LIBRARY   SLATEC
!***TYPE      SINGLE PRECISION (PINITM-S, DPINTM-D)
!***AUTHOR  Hanson, R. J., (SNLA)
!           Wisniewski, J. A., (SNLA)
!***DESCRIPTION
!
!     PINITM LIMITS THE TYPE OF STORAGE TO A SEQUENTIAL SCHEME.
!     THE MATRIX IS STORED BY COLUMNS.
!     SPARSE MATRIX INITIALIZATION SUBROUTINE.
!
!            M=NUMBER OF ROWS OF THE MATRIX.
!            N=NUMBER OF COLUMNS OF THE MATRIX.
!  SX(*),IX(*)=THE WORK ARRAYS WHICH ARE USED TO STORE THE SPARSE
!              MATRIX.  THESE ARRAYS ARE AUTOMATICALLY MAINTAINED BY
!              THE PACKAGE FOR THE USER.
!          LMX=LENGTH OF THE WORK ARRAY SX(*).
!              LMX MUST BE AT LEAST N+7 WHERE
!              FOR GREATEST EFFICIENCY LMX SHOULD BE AT LEAST N+NZ+6
!              WHERE NZ IS THE MAXIMUM NUMBER OF NONZEROES TO BE
!              STORED IN THE MATRIX.  VALUES OF LMX BETWEEN N+7 AND
!              N+NZ+6 WILL CAUSE DEMAND PAGING TO OCCUR.
!              THIS IS IMPLEMENTED BY THE PACKAGE.
!              IX(*) MUST BE DIMENSIONED AT LEAST LMX
!      IPAGEF=UNIT NUMBER WHERE DEMAND PAGES WILL BE STORED.
!
!     THIS SUBROUTINE IS A MODIFICATION OF THE SUBROUTINE LINITM,
!     SANDIA LABS. REPT. SAND78-0785.
!     MODIFICATIONS BY K.L. HIEBERT AND R.J. HANSON
!     REVISED 811130-1000
!     REVISED YYMMDD-HHMM
!
!***SEE ALSO  SPLP
!***ROUTINES CALLED  XERMSG
!***REVISION HISTORY  (YYMMDD)
!   811215  DATE WRITTEN
!   890831  Modified array declarations.  (WRB)
!   891214  Prologue converted to Version 4.0 format.  (BAB)
!   900315  CALLs to XERROR changed to CALLs to XERMSG.  (THJ)
!   900328  Added TYPE section.  (WRB)
!   910403  Updated AUTHOR and DESCRIPTION sections.  (WRB)
!***END PROLOGUE  PINITM
  REAL SX(LMX),ZERO,ONE
  DIMENSION IX(*)
  SAVE ZERO, ONE
  DATA ZERO,ONE /0.E0,1.E0/
!***FIRST EXECUTABLE STATEMENT  PINITM
  IOPT=1
!
!     CHECK FOR INPUT ERRORS.
!
  if (.NOT.(M <= 0 .OR. N <= 0)) go to 20002
  NERR=55
  call XERMSG ('SLATEC', 'PINITM', &
     'MATRIX DIMENSION M OR N  <=  0.', NERR, IOPT)
!
!     VERIFY if VALUE OF LMX IS LARGE ENOUGH.
!
20002 if (.NOT.(LMX < N+7)) go to 20005
  NERR=55
  call XERMSG ('SLATEC', 'PINITM', &
     'THE VALUE OF LMX IS TOO SMALL.', NERR, IOPT)
!
!     INITIALIZE DATA STRUCTURE INDEPENDENT VALUES.
!
20005 SX(1)=ZERO
  SX(2)=ZERO
  SX(3)=IPAGEF
  IX(1)=LMX
  IX(2)=M
  IX(3)=N
  IX(4)=0
  SX(LMX-1)=ZERO
  SX(LMX)=-ONE
  IX(LMX-1)=-1
  LP4=N+4
!
!     INITIALIZE DATA STRUCTURE DEPENDENT VALUES.
!
  I=4
  N20008=LP4
  go to 20009
20008 I=I+1
20009 if ((N20008-I) < 0) go to 20010
  SX(I)=ZERO
  go to 20008
20010 I=5
  N20012=LP4
  go to 20013
20012 I=I+1
20013 if ((N20012-I) < 0) go to 20014
  IX(I)=LP4
  go to 20012
20014 SX(N+5)=ZERO
  IX(N+5)=0
  IX(LMX)=0
!
!     INITIALIZATION COMPLETE.
!
  return
end
