subroutine PRWVIR (KEY, IPAGE, LPG, SX, IX)
!
!! PRWVIR is subsidiary to SPLP.
!
!***LIBRARY   SLATEC
!***TYPE      SINGLE PRECISION (PRWVIR-S, DPRWVR-D)
!***AUTHOR  Hanson, R. J., (SNLA)
!           Wisniewski, J. A., (SNLA)
!***DESCRIPTION
!
!     PRWVIR LIMITS THE TYPE OF STORAGE TO A SEQUENTIAL SPARSE MATRIX
!     STORAGE SCHEME.  THE PAGE STORAGE IS ON RANDOM ACCESS DISK.
!     PRWVIR IS PART OF THE SPARSE LP PACKAGE, SPLP.
!
!     KEY       IS A FLAG WHICH INDICATES WHETHER A READ OR WRITE
!               OPERATION IS TO BE PERFORMED. A VALUE OF KEY=1 INDICATES
!               A READ. A VALUE OF KEY=2 INDICATES A WRITE.
!     IPAGE     IS THE PAGE OF MATRIX MN WE ARE ACCESSING.
!     LPG       IS THE LENGTH OF THE PAGE.
!   SX(*),IX(*) IS THE MATRIX DATA.
!
!     THIS SUBROUTINE IS A MODIFICATION OF THE SUBROUTINE LRWVIR,
!     SANDIA LABS. REPT. SAND78-0785.
!     MODIFICATIONS BY K.L. HIEBERT AND R.J. HANSON
!
!***SEE ALSO  SPLP
!***ROUTINES CALLED  SOPENM, SREADP, SWRITP
!***REVISION HISTORY  (YYMMDD)
!   811215  DATE WRITTEN
!   891009  Removed unreferenced variables.  (WRB)
!   891214  Prologue converted to Version 4.0 format.  (BAB)
!   900328  Added TYPE section.  (WRB)
!   910403  Updated AUTHOR and DESCRIPTION sections.  (WRB)
!***END PROLOGUE  PRWVIR
  DIMENSION IX(*)
  REAL SX(*),ZERO,ONE
  LOGICAL FIRST
  SAVE ZERO, ONE
  DATA ZERO,ONE/0.E0,1.E0/
!***FIRST EXECUTABLE STATEMENT  PRWVIR
!
!     COMPUTE STARTING ADDRESS OF PAGE.
!
  IPAGEF=SX(3)
  ISTART = IX(3) + 5
!
!     OPEN RANDOM ACCESS FILE NUMBER IPAGEF, if FIRST PAGE WRITE.
!
  FIRST=SX(4) == ZERO
  if (.NOT.(FIRST)) go to 20002
  call SOPENM(IPAGEF,LPG)
  SX(4)=ONE
!
!     PERFORM EITHER A READ OR A WRITE.
!
20002 IADDR = 2*IPAGE - 1
  if (.NOT.(KEY == 1)) go to 20005
  call SREADP(IPAGEF,IX(ISTART),SX(ISTART),LPG,IADDR)
  go to 20006
20005 if (.NOT.(KEY == 2)) go to 10001
  call SWRITP(IPAGEF,IX(ISTART),SX(ISTART),LPG,IADDR)
10001 CONTINUE
20006 RETURN
end
