subroutine SDATRP (X, XOUT, YOUT, YPOUT, NEQ, KOLD, PHI, PSI)
!
!! SDATRP is the interpolation routine for SDASSL.
!
!***LIBRARY   SLATEC (DASSL)
!***TYPE      SINGLE PRECISION (SDATRP-S, DDATRP-D)
!***AUTHOR  Petzold, Linda R., (LLNL)
!***DESCRIPTION
!-----------------------------------------------------------------------
!     THE METHODS IN SUBROUTINE SDASTP USE POLYNOMIALS
!     TO APPROXIMATE THE SOLUTION. SDATRP APPROXIMATES THE
!     SOLUTION AND ITS DERIVATIVE AT TIME XOUT BY EVALUATING
!     ONE OF THESE POLYNOMIALS, AND ITS DERIVATIVE,THERE.
!     INFORMATION DEFINING THIS POLYNOMIAL IS PASSED FROM
!     SDASTP, SO SDATRP CANNOT BE USED ALONE.
!
!     THE PARAMETERS ARE:
!     X     THE CURRENT TIME IN THE INTEGRATION.
!     XOUT  THE TIME AT WHICH THE SOLUTION IS DESIRED
!     YOUT  THE INTERPOLATED APPROXIMATION TO Y AT XOUT
!           (THIS IS OUTPUT)
!     YPOUT THE INTERPOLATED APPROXIMATION TO YPRIME AT XOUT
!           (THIS IS OUTPUT)
!     NEQ   NUMBER OF EQUATIONS
!     KOLD  ORDER USED ON LAST SUCCESSFUL STEP
!     PHI   ARRAY OF SCALED DIVIDED DIFFERENCES OF Y
!     PSI   ARRAY OF PAST STEPSIZE HISTORY
!-----------------------------------------------------------------------
!***ROUTINES CALLED  (NONE)
!***REVISION HISTORY  (YYMMDD)
!   830315  DATE WRITTEN
!   901009  Finished conversion to SLATEC 4.0 format (F.N.Fritsch)
!   901019  Merged changes made by C. Ulrich with SLATEC 4.0 format.
!   901026  Added explicit declarations for all variables and minor
!           cosmetic changes to prologue.  (FNF)
!***END PROLOGUE  SDATRP
!
  INTEGER  NEQ, KOLD
  REAL  X, XOUT, YOUT(*), YPOUT(*), PHI(NEQ,*), PSI(*)
!
  INTEGER  I, J, KOLDP1
  REAL  C, D, GAMMA, TEMP1
!
!***FIRST EXECUTABLE STATEMENT  SDATRP
  KOLDP1=KOLD+1
  TEMP1=XOUT-X
  DO 10 I=1,NEQ
     YOUT(I)=PHI(I,1)
10       YPOUT(I)=0.0E0
  C=1.0E0
  D=0.0E0
  GAMMA=TEMP1/PSI(1)
  DO 30 J=2,KOLDP1
     D=D*GAMMA+C/PSI(J-1)
     C=C*GAMMA
     GAMMA=(TEMP1+PSI(J-1))/PSI(J)
     DO 20 I=1,NEQ
        YOUT(I)=YOUT(I)+C*PHI(I,J)
20          YPOUT(I)=YPOUT(I)+D*PHI(I,J)
30       CONTINUE
  return
!
!------END OF SUBROUTINE SDATRP------
end
