subroutine SMOUT (M, N, LDA, A, IFMT, IDIGIT)
!
!! SMOUT prints a single precision matrix.
!
!***SUBSIDIARY
!***PURPOSE  Subsidiary to FC and SBOCLS
!***LIBRARY   SLATEC
!***TYPE      SINGLE PRECISION (SMOUT-S, DMOUT-D)
!***AUTHOR  (UNKNOWN)
!***DESCRIPTION
!
!     SINGLE PRECISION MATRIX OUTPUT ROUTINE.
!
!  INPUT..
!
!  M,N,LDA,A(*,*) PRINT THE SINGLE PRECISION ARRAY A(I,J),I  = 1,...,M,
!                 J=1,...,N, ON OUTPUT UNIT LOUT=6. LDA IS THE DECLARED
!                 FIRST DIMENSION OF A(*,*) AS SPECIFIED IN THE CALLING
!                 PROGRAM. THE HEADING IN THE FORTRAN FORMAT STATEMENT
!                 IFMT(*), DESCRIBED BELOW, IS PRINTED AS A FIRST STEP.
!                 THE COMPONENTS A(I,J) ARE INDEXED, ON OUTPUT, IN A
!                 PLEASANT FORMAT.
!  IFMT(*)        A FORTRAN FORMAT STATEMENT. THIS IS PRINTED ON
!                 OUTPUT UNIT LOUT=6 WITH THE VARIABLE FORMAT FORTRAN
!                 STATEMENT
!                       WRITE(LOUT,IFMT).
!  IDIGIT         PRINT AT LEAST ABS(IDIGIT) DECIMAL DIGITS PER NUMBER.
!                 THE SUBPROGRAM WILL CHOOSE THAT INTEGER 4,6,10, OR 14
!                 WHICH WILL PRINT AT LEAST ABS(IDIGIT) NUMBER OF
!                 PLACES.  if IDIGIT < 0, 72 PRINTING COLUMNS ARE
!                 UTILIZED TO WRITE EACH LINE OF OUTPUT OF THE ARRAY
!                 A(*,*). (THIS CAN BE USED ON MOST TIME-SHARING
!                 TERMINALS).  if IDIGIT >= 0, 133 PRINTING COLUMNS ARE
!                 UTILIZED. (THIS CAN BE USED ON MOST LINE PRINTERS).
!
!  EXAMPLE..
!
!  PRINT AN ARRAY CALLED (SIMPLEX TABLEAU   ) OF SIZE 10 BY 20 SHOWING
!  6 DECIMAL DIGITS PER NUMBER. THE USER IS RUNNING ON A TIME-SHARING
!  SYSTEM WITH A 72 COLUMN OUTPUT DEVICE.
!
!     DIMENSION TABLEU(20,20)
!     M = 10
!     N = 20
!     LDTABL = 20
!     IDIGIT = -6
!     call SMOUT(M,N,LDTABL,TABLEU,21H(16H1SIMPLEX TABLEAU),IDIGIT)
!
!***SEE ALSO  FC, SBOCLS
!***ROUTINES CALLED  I1MACH
!***REVISION HISTORY  (YYMMDD)
!   780801  DATE WRITTEN
!   890531  Changed all specific intrinsics to generic.  (WRB)
!   891107  Added comma after 1P edit descriptor in FORMAT
!           statements.  (WRB)
!   891214  Prologue converted to Version 4.0 format.  (BAB)
!   900328  Added TYPE section.  (WRB)
!***END PROLOGUE  SMOUT
  DIMENSION A(LDA,*)
  CHARACTER IFMT*(*),ICOL*3
  SAVE ICOL
  DATA ICOL /'COL'/
!***FIRST EXECUTABLE STATEMENT  SMOUT
  LOUT=I1MACH(2)
  WRITE(LOUT,IFMT)
  if ( M <= 0.OR.N <= 0.OR.LDA <= 0) RETURN
  NDIGIT = IDIGIT
  if ( IDIGIT == 0) NDIGIT = 4
  if ( IDIGIT >= 0) go to 80
!
  NDIGIT = -IDIGIT
  if ( NDIGIT > 4) go to 20
!
  DO 10 K1=1,N,5
  K2 = MIN(N,K1+4)
  WRITE(LOUT,1000) (ICOL,I,I = K1, K2)
  DO 10 I = 1, M
  WRITE(LOUT,1004) I,(A(I,J),J = K1, K2)
   10 CONTINUE
  return
!
   20 CONTINUE
  if ( NDIGIT > 6) go to 40
!
  DO 30 K1=1,N,4
  K2 = MIN(N,K1+3)
  WRITE(LOUT,1001) (ICOL,I,I = K1, K2)
  DO 30 I = 1, M
  WRITE(LOUT,1005) I,(A(I,J),J = K1, K2)
   30 CONTINUE
  return
!
   40 CONTINUE
  if ( NDIGIT > 10) go to 60
!
  DO 50 K1=1,N,3
  K2=MIN(N,K1+2)
  WRITE(LOUT,1002) (ICOL,I,I = K1, K2)
  DO 50 I = 1, M
  WRITE(LOUT,1006) I,(A(I,J),J = K1, K2)
   50 CONTINUE
  return
!
   60 CONTINUE
  DO 70 K1=1,N,2
  K2 = MIN(N,K1+1)
  WRITE(LOUT,1003) (ICOL,I,I = K1, K2)
  DO 70 I = 1, M
  WRITE(LOUT,1007) I,(A(I,J),J = K1, K2)
   70 CONTINUE
  return
!
   80 CONTINUE
  if ( NDIGIT > 4) go to 100
!
  DO 90 K1=1,N,10
  K2 = MIN(N,K1+9)
  WRITE(LOUT,1000) (ICOL,I,I = K1, K2)
  DO 90 I = 1, M
  WRITE(LOUT,1004) I,(A(I,J),J = K1, K2)
   90 CONTINUE
  return
!
  100 CONTINUE
  if ( NDIGIT > 6) go to 120
!
  DO 110 K1=1,N,8
  K2 = MIN(N,K1+7)
  WRITE(LOUT,1001) (ICOL,I,I = K1, K2)
  DO 110 I = 1, M
  WRITE(LOUT,1005) I,(A(I,J),J = K1, K2)
  110 CONTINUE
  return
!
  120 CONTINUE
  if ( NDIGIT > 10) go to 140
!
  DO 130 K1=1,N,6
  K2 = MIN(N,K1+5)
  WRITE(LOUT,1002) (ICOL,I,I = K1, K2)
  DO 130 I = 1, M
  WRITE(LOUT,1006) I,(A(I,J),J = K1, K2)
  130 CONTINUE
  return
!
  140 CONTINUE
  DO 150 K1=1,N,5
  K2 = MIN(N,K1+4)
  WRITE(LOUT,1003) (ICOL,I,I = K1, K2)
  DO 150 I = 1, M
  WRITE(LOUT,1007) I,(A(I,J),J = K1, K2)
  150 CONTINUE
  return
 1000 FORMAT(10X,10(4X,A,I4,1X))
 1001 FORMAT(10X,8(5X,A,I4,2X))
 1002 FORMAT(10X,6(7X,A,I4,4X))
 1003 FORMAT(10X,5(9X,A,I4,6X))
 1004 FORMAT(1X,3HROW,I4,2X,1P,10E12.3)
 1005 FORMAT(1X,3HROW,I4,2X,1P,8E14.5)
 1006 FORMAT(1X,3HROW,I4,2X,1P,6E18.9)
 1007 FORMAT(1X,3HROW,I4,2X,1P,5E22.13)
end
