subroutine SOPENM (IPAGE, LPAGE)
!
!! SOPENM is subsidiary to SPLP.
!
!***LIBRARY   SLATEC
!***TYPE      ALL (SOPENM-A)
!***AUTHOR  (UNKNOWN)
!***DESCRIPTION
!
!     1. OPEN UNIT NUMBER IPAGEF AS A RANDOM ACCESS FILE.
!
!     2. THE RECORD LENGTH IS CONSTANT=LPG.
!
!***SEE ALSO  SPLP
!***ROUTINES CALLED  XERMSG
!***REVISION HISTORY  (YYMMDD)
!   811215  DATE WRITTEN
!   890605  Corrected references to XERRWV.  (WRB)
!   891214  Prologue converted to Version 4.0 format.  (BAB)
!   900402  Added TYPE section.  (WRB)
!   900510  Convert XERRWV calls to XERMSG calls.  (RWC)
!***END PROLOGUE  SOPENM
  CHARACTER*8 XERN1
!
!***FIRST EXECUTABLE STATEMENT  SOPENM
  IPAGEF=IPAGE
  LPG   =LPAGE
  OPEN(UNIT=IPAGEF,IOSTAT=IOS,ERR=100,STATUS='UNKNOWN', &
  ACCESS='DIRECT',FORM='UNFORMATTED',RECL=LPG)
  return
!
 100  WRITE (XERN1, '(I8)') IOS
  call XERMSG ('SLATEC', 'SOPENM', &
     'IN SPLP, OPEN HAS ERROR FLAG = ' // XERN1, 100, 1)
  return
end
