subroutine SPINCW (MRELAS, NVARS, LMX, LBM, NPP, JSTRT, IBASIS, &
     IMAT, IBRC, IPR, IWR, IND, IBB, COSTSC, GG, ERDNRM, DULNRM, &
     AMAT, BASMAT, CSC, WR, WW, RZ, RG, COSTS, COLNRM, DUALS, &
     STPEDG)
!
!! SPINCW is subsidiary to SPLP.
!
!***LIBRARY   SLATEC
!***TYPE      SINGLE PRECISION (SPINCW-S, DPINCW-D)
!***AUTHOR  (UNKNOWN)
!***DESCRIPTION
!
!     THE EDITING REQUIRED TO CONVERT THIS SUBROUTINE FROM SINGLE TO
!     DOUBLE PRECISION INVOLVES THE FOLLOWING CHARACTER STRING CHANGES.
!
!     USE AN EDITING COMMAND (CHANGE) /STRING-1/(TO)STRING-2/,
!     REAL (12 BLANKS)/DOUBLE PRECISION/,/SCOPY/DCOPY/,/SDOT/DDOT/.
!
!     THIS SUBPROGRAM IS PART OF THE SPLP( ) PACKAGE.
!     IT IMPLEMENTS THE PROCEDURE (INITIALIZE REDUCED COSTS AND
!     STEEPEST EDGE WEIGHTS).
!
!***SEE ALSO  SPLP
!***ROUTINES CALLED  IPLOC, LA05BS, PRWPGE, SCOPY, SDOT
!***REVISION HISTORY  (YYMMDD)
!   811215  DATE WRITTEN
!   890531  Changed all specific intrinsics to generic.  (WRB)
!   890605  Removed unreferenced labels.  (WRB)
!   891214  Prologue converted to Version 4.0 format.  (BAB)
!   900328  Added TYPE section.  (WRB)
!***END PROLOGUE  SPINCW
  INTEGER IBASIS(*),IMAT(*),IBRC(LBM,2),IPR(*),IWR(*),IND(*),IBB(*)
  REAL             AMAT(*),BASMAT(*),CSC(*),WR(*),WW(*),RZ(*),RG(*), &
   COSTS(*),COLNRM(*),DUALS(*),COSTSC,ERDNRM,DULNRM,GG,ONE,RZJ, &
   SCALR,ZERO,RCOST
  LOGICAL STPEDG,PAGEPL,TRANS
!***FIRST EXECUTABLE STATEMENT  SPINCW
  LPG=LMX-(NVARS+4)
  ZERO=0.
  ONE=1.
!
!     FORM REDUCED COSTS, RZ(*), AND STEEPEST EDGE WEIGHTS, RG(*).
  PAGEPL=.TRUE.
  RZ(1)=ZERO
  call SCOPY(NVARS+MRELAS,RZ,0,RZ,1)
  RG(1)=ONE
  call SCOPY(NVARS+MRELAS,RG,0,RG,1)
  NNEGRC=0
  J=JSTRT
20002 if (.NOT.(IBB(J) <= 0)) go to 20004
  PAGEPL=.TRUE.
  go to 20005
!
!     THESE ARE NONBASIC INDEPENDENT VARIABLES. THE COLS. ARE IN SPARSE
!     MATRIX FORMAT.
20004 if (.NOT.(J <= NVARS)) go to 20007
  RZJ=COSTSC*COSTS(J)
  WW(1)=ZERO
  call SCOPY(MRELAS,WW,0,WW,1)
  if (.NOT.(J == 1)) go to 20010
  ILOW=NVARS+5
  go to 20011
20010 ILOW=IMAT(J+3)+1
20011 CONTINUE
  if (.NOT.(PAGEPL)) go to 20013
  IL1=IPLOC(ILOW,AMAT,IMAT)
  if (.NOT.(IL1 >= LMX-1)) go to 20016
  ILOW=ILOW+2
  IL1=IPLOC(ILOW,AMAT,IMAT)
20016 CONTINUE
  IPAGE=ABS(IMAT(LMX-1))
  go to 20014
20013 IL1=IHI+1
20014 CONTINUE
  IHI=IMAT(J+4)-(ILOW-IL1)
20019 IU1=MIN(LMX-2,IHI)
  if (.NOT.(IL1 > IU1)) go to 20021
  go to 20020
20021 CONTINUE
  DO 60 I=IL1,IU1
  RZJ=RZJ-AMAT(I)*DUALS(IMAT(I))
  WW(IMAT(I))=AMAT(I)*CSC(J)
60    CONTINUE
  if (.NOT.(IHI <= LMX-2)) go to 20024
  go to 20020
20024 CONTINUE
  IPAGE=IPAGE+1
  KEY=1
  call PRWPGE(KEY,IPAGE,LPG,AMAT,IMAT)
  IL1=NVARS+5
  IHI=IHI-LPG
  go to 20019
20020 PAGEPL=IHI == (LMX-2)
  RZ(J)=RZJ*CSC(J)
  if (.NOT.(STPEDG)) go to 20027
  TRANS=.FALSE.
  call LA05BS(BASMAT,IBRC,LBM,MRELAS,IPR,IWR,WR,GG,WW,TRANS)
  RG(J)=SDOT(MRELAS,WW,1,WW,1)+ONE
20027 CONTINUE
!
!     THESE ARE NONBASIC DEPENDENT VARIABLES. THE COLS. ARE IMPLICITLY
!     DEFINED.
  go to 20008
20007 PAGEPL=.TRUE.
  WW(1)=ZERO
  call SCOPY(MRELAS,WW,0,WW,1)
  SCALR=-ONE
  if (IND(J) == 2) SCALR=ONE
  I=J-NVARS
  RZ(J)=-SCALR*DUALS(I)
  WW(I)=SCALR
  if (.NOT.(STPEDG)) go to 20030
  TRANS=.FALSE.
  call LA05BS(BASMAT,IBRC,LBM,MRELAS,IPR,IWR,WR,GG,WW,TRANS)
  RG(J)=SDOT(MRELAS,WW,1,WW,1)+ONE
20030 CONTINUE
  CONTINUE
20008 CONTINUE
!
20005 RCOST=RZ(J)
  if (MOD(IBB(J),2) == 0) RCOST=-RCOST
  if (IND(J) == 4) RCOST=-ABS(RCOST)
  CNORM=ONE
  if (J <= NVARS) CNORM=COLNRM(J)
  if (RCOST+ERDNRM*DULNRM*CNORM < ZERO) NNEGRC=NNEGRC+1
  J=MOD(J,MRELAS+NVARS)+1
  if (.NOT.(NNEGRC >= NPP .OR. J == JSTRT)) go to 20033
  go to 20003
20033 go to 20002
20003 JSTRT=J
  return
end
