subroutine SPLPFL (MRELAS, NVARS, IENTER, ILEAVE, IBASIS, IND, &
     IBB, THETA, DIRNRM, RPRNRM, CSC, WW, BL, BU, ERP, RPRIM, &
     PRIMAL, FINITE, ZEROLV)
!
!! SPLPFL is subsidiary to SPLP.
!
!***LIBRARY   SLATEC
!***TYPE      SINGLE PRECISION (SPLPFL-S, DPLPFL-D)
!***AUTHOR  (UNKNOWN)
!***DESCRIPTION
!
!     THE EDITING REQUIRED TO CONVERT THIS SUBROUTINE FROM SINGLE TO
!     DOUBLE PRECISION INVOLVES THE FOLLOWING CHARACTER STRING CHANGES.
!
!     USE AN EDITING COMMAND (CHANGE) /STRING-1/(TO)STRING-2/.
!     /REAL (12 BLANKS)/DOUBLE PRECISION/.
!
!     THIS SUBPROGRAM IS PART OF THE SPLP( ) PACKAGE.
!     IT IMPLEMENTS THE PROCEDURE (CHOOSE VARIABLE TO LEAVE BASIS).
!     REVISED 811130-1045
!     REVISED YYMMDD-HHMM
!
!***SEE ALSO  SPLP
!***ROUTINES CALLED  (NONE)
!***REVISION HISTORY  (YYMMDD)
!   811215  DATE WRITTEN
!   890531  Changed all specific intrinsics to generic.  (WRB)
!   890605  Removed unreferenced labels.  (WRB)
!   891214  Prologue converted to Version 4.0 format.  (BAB)
!   900328  Added TYPE section.  (WRB)
!***END PROLOGUE  SPLPFL
  INTEGER IBASIS(*),IND(*),IBB(*)
  REAL             CSC(*),WW(*),BL(*),BU(*),ERP(*),RPRIM(*), &
   PRIMAL(*),BOUND,DIRNRM,RATIO,RPRNRM,THETA,ZERO
  LOGICAL FINITE,ZEROLV
!***FIRST EXECUTABLE STATEMENT  SPLPFL
  ZERO=0.E0
!
!     SEE if THE ENTERING VARIABLE IS RESTRICTING THE STEP LENGTH
!     BECAUSE OF AN UPPER BOUND.
  FINITE=.FALSE.
  J=IBASIS(IENTER)
  if (.NOT.(IND(J) == 3)) go to 20002
  THETA=BU(J)-BL(J)
  if ( J <= NVARS)THETA=THETA/CSC(J)
  FINITE=.TRUE.
  ILEAVE=IENTER
!
!     NOW USE THE BASIC VARIABLES TO POSSIBLY RESTRICT THE STEP
!     LENGTH EVEN FURTHER.
20002 I=1
  N20005=MRELAS
  go to 20006
20005 I=I+1
20006 if ((N20005-I) < 0) go to 20007
  J=IBASIS(I)
!
!     if THIS IS A FREE VARIABLE, DO NOT USE IT TO
!     RESTRICT THE STEP LENGTH.
  if (.NOT.(IND(J) == 4)) go to 20009
  go to 20005
!
!     if DIRECTION COMPONENT IS ABOUT ZERO, IGNORE IT FOR COMPUTING
!     THE STEP LENGTH.
20009 if (.NOT.(ABS(WW(I)) <= DIRNRM*ERP(I))) go to 20012
  go to 20005
20012 if (.NOT.(WW(I) > ZERO)) go to 20015
!
!     if RPRIM(I) IS ESSENTIALLY ZERO, SET RATIO TO ZERO AND EXIT LOOP.
  if (.NOT.(ABS(RPRIM(I)) <= RPRNRM*ERP(I))) go to 20018
  THETA=ZERO
  ILEAVE=I
  FINITE=.TRUE.
  go to 20008
!
!     THE VALUE OF RPRIM(I) WILL DECREASE ONLY TO ITS LOWER BOUND OR
!     ONLY TO ITS UPPER BOUND.  if IT DECREASES TO ITS
!     UPPER BOUND, THEN RPRIM(I) HAS ALREADY BEEN TRANSLATED
!     TO ITS UPPER BOUND AND NOTHING NEEDS TO BE DONE TO IBB(J).
20018 if (.NOT.(RPRIM(I) > ZERO)) go to 10001
  RATIO=RPRIM(I)/WW(I)
  if (.NOT.(.NOT.FINITE)) go to 20021
  ILEAVE=I
  THETA=RATIO
  FINITE=.TRUE.
  go to 20022
20021 if (.NOT.(RATIO < THETA)) go to 10002
  ILEAVE=I
  THETA=RATIO
10002 CONTINUE
20022 CONTINUE
  go to 20019
!
!     THE VALUE RPRIM(I) < ZERO WILL NOT RESTRICT THE STEP.
10001 CONTINUE
!
!     THE DIRECTION COMPONENT IS NEGATIVE, THEREFORE THE VARIABLE WILL
!     INCREASE.
20019 go to 20016
!
!     if THE VARIABLE IS LESS THAN ITS LOWER BOUND, IT CAN
!     INCREASE ONLY TO ITS LOWER BOUND.
20015 if (.NOT.(PRIMAL(I+NVARS) < ZERO)) go to 20024
  RATIO=RPRIM(I)/WW(I)
  if (RATIO < ZERO) RATIO=ZERO
  if (.NOT.(.NOT.FINITE)) go to 20027
  ILEAVE=I
  THETA=RATIO
  FINITE=.TRUE.
  go to 20028
20027 if (.NOT.(RATIO < THETA)) go to 10003
  ILEAVE=I
  THETA=RATIO
10003 CONTINUE
20028 CONTINUE
!
!     if THE BASIC VARIABLE IS FEASIBLE AND IS NOT AT ITS UPPER BOUND,
!     THEN IT CAN INCREASE TO ITS UPPER BOUND.
  go to 20025
20024 if (.NOT.(IND(J) == 3 .AND. PRIMAL(I+NVARS) == ZERO)) go to 10004
  BOUND=BU(J)-BL(J)
  if ( J <= NVARS) BOUND=BOUND/CSC(J)
  RATIO=(BOUND-RPRIM(I))/(-WW(I))
  if (.NOT.(.NOT.FINITE)) go to 20030
  ILEAVE=-I
  THETA=RATIO
  FINITE=.TRUE.
  go to 20031
20030 if (.NOT.(RATIO < THETA)) go to 10005
  ILEAVE=-I
  THETA=RATIO
10005 CONTINUE
20031 CONTINUE
  CONTINUE
10004 CONTINUE
20025 CONTINUE
20016 go to 20005
20007 CONTINUE
!
!     if STEP LENGTH IS FINITE, SEE IF STEP LENGTH IS ABOUT ZERO.
20008 if (.NOT.(FINITE)) go to 20033
  ZEROLV=.TRUE.
  I=1
  N20036=MRELAS
  go to 20037
20036 I=I+1
20037 if ((N20036-I) < 0) go to 20038
  ZEROLV=ZEROLV.AND. ABS(THETA*WW(I)) <= ERP(I)*RPRNRM
  if (.NOT.(.NOT. ZEROLV)) go to 20040
  go to 20039
20040 go to 20036
20038 CONTINUE
20039 CONTINUE
20033 CONTINUE
  return
end
