subroutine SWRITP (IPAGE, LIST, RLIST, LPAGE, IREC)
!
!! SWRITP writes a record out to a file for SPLP.
!
!***SUBSIDIARY
!***PURPOSE  Subsidiary to SPLP
!***LIBRARY   SLATEC
!***TYPE      SINGLE PRECISION (SWRITP-S, DWRITP-D)
!***AUTHOR  (UNKNOWN)
!***DESCRIPTION
!
!     WRITE RECORD NUMBER IRECN, OF LENGTH LPG, FROM STORAGE
!     ARRAY LIST(*) ONTO UNIT NUMBER IPAGEF.
!     WRITE RECORD NUMBER IRECN+1, OF LENGTH LPG, ONTO UNIT
!     NUMBER IPAGEF FROM THE STORAGE ARRAY RLIST(*).
!
!     TO CHANGE THIS PROGRAM UNIT TO DOUBLE PRECISION CHANGE
!     /REAL (12 BLANKS)/ TO /DOUBLE PRECISION/.
!
!***SEE ALSO  SPLP
!***ROUTINES CALLED  XERMSG
!***REVISION HISTORY  (YYMMDD)
!   811215  DATE WRITTEN
!   890605  Corrected references to XERRWV.  (WRB)
!   891214  Prologue converted to Version 4.0 format.  (BAB)
!   900328  Added TYPE section.  (WRB)
!   900510  Convert XERRWV calls to XERMSG calls.  (RWC)
!***END PROLOGUE  SWRITP
  INTEGER LIST(*)
  REAL             RLIST(*)
  CHARACTER*8 XERN1, XERN2
!***FIRST EXECUTABLE STATEMENT  SWRITP
  IPAGEF=IPAGE
  LPG   =LPAGE
  IRECN =IREC
  WRITE(IPAGEF,REC=IRECN,ERR=100)(LIST(I),I=1,LPG)
  WRITE(IPAGEF,REC=IRECN+1,ERR=100)(RLIST(I),I=1,LPG)
  return
!
  100 WRITE (XERN1, '(I8)') LPG
  WRITE (XERN2, '(I8)') IRECN
  call XERMSG ('SLATEC', 'SWRITP', 'IN SPLP, LGP = ' // XERN1 // &
     ' IRECN = ' // XERN2, 100, 1)
  return
end
