subroutine ZDIV (AR, AI, BR, BI, CR, CI)
!
!! ZDIV is subsidiary to ZBESH, ZBESI, ZBESJ, ZBESK, ZBESY, ZAIRY and ZBIRY.
!
!***LIBRARY   SLATEC
!***TYPE      ALL (ZDIV-A)
!***AUTHOR  Amos, D. E., (SNL)
!***DESCRIPTION
!
!     DOUBLE PRECISION COMPLEX DIVIDE C=A/B.
!
!***SEE ALSO  ZAIRY, ZBESH, ZBESI, ZBESJ, ZBESK, ZBESY, ZBIRY
!***ROUTINES CALLED  ZABS
!***REVISION HISTORY  (YYMMDD)
!   830501  DATE WRITTEN
!   910415  Prologue converted to Version 4.0 format.  (BAB)
!***END PROLOGUE  ZDIV
  DOUBLE PRECISION AR, AI, BR, BI, CR, CI, BM, CA, CB, CC, CD
  DOUBLE PRECISION ZABS
  EXTERNAL ZABS
!***FIRST EXECUTABLE STATEMENT  ZDIV
  BM = 1.0D0/ZABS(BR,BI)
  CC = BR*BM
  CD = BI*BM
  CA = (AR*CC+AI*CD)*BM
  CB = (AI*CC-AR*CD)*BM
  CR = CA
  CI = CB
  return
end
