subroutine ZMLT (AR, AI, BR, BI, CR, CI)
!
!! ZMLT is subsidiary to ZBESH, ZBESI, ZBESJ, ZBESK, ZBESY, ZAIRY and ZBIRY.
!
!***LIBRARY   SLATEC
!***TYPE      ALL (ZMLT-A)
!***AUTHOR  Amos, D. E., (SNL)
!***DESCRIPTION
!
!     DOUBLE PRECISION COMPLEX MULTIPLY, C=A*B.
!
!***SEE ALSO  ZAIRY, ZBESH, ZBESI, ZBESJ, ZBESK, ZBESY, ZBIRY
!***ROUTINES CALLED  (NONE)
!***REVISION HISTORY  (YYMMDD)
!   830501  DATE WRITTEN
!   910415  Prologue converted to Version 4.0 format.  (BAB)
!***END PROLOGUE  ZMLT
  DOUBLE PRECISION AR, AI, BR, BI, CR, CI, CA, CB
!***FIRST EXECUTABLE STATEMENT  ZMLT
  CA = AR*BR - AI*BI
  CB = AR*BI + AI*BR
  CR = CA
  CI = CB
  return
end
